version: "3"

services:
  pushkin:
    build: ./pushkin
    environment:
      KAFKA_BROKER_URL: broker:9092
      MARS_BW_TOPIC: queue.bwimg
      MARS_COLOR_TOPIC: stream.colorimg
  tolstoy:
    build: ./tolstoy
    environment:
      KAFKA_BROKER_URL: broker:9092
      MARS_BW_TOPIC: queue.bwimg
      MARS_COLOR_TOPIC: stream.colorimg
  nabokov:
    build: ./nabokov
    environment:
      KAFKA_BROKER_URL: broker:9092
      MARS_COLOR_TOPIC: stream.colorimg

# give this cluster access to kafka-network
networks:
  default:
    external:
      name: kafka-network
